version: "3"

networks:
  traefik-public:
    external: true
  internal:
    external: false
    
services:
  files:
    image: zate75/files
    container_name: files
    restart: on-failure
    entrypoint: ["./files","-d","./stuff"]
    labels:
      - traefik.backend=files
      - traefik.frontend.rule=Host:files.zate.org
      - traefik.docker.network=traefik-public
      - traefik.enable=true
      - traefik.port=8100
      - traefik.tags=traefik-public
      # Traefik service that listens to HTTP
      - traefik.redirectorservice.frontend.entryPoints=http
      - traefik.redirectorservice.frontend.redirect.entryPoint=https
      # Traefik service that listens to HTTPS
      - traefik.webservice.frontend.entryPoints=https
    networks:
      - internal
      - traefik-public
    volumes:
      - /root/docker/stuff:/stuff:cached
    deploy:
      placement:
        constraints:
          - node.role == manager
#
