version: "3"

networks:
  proxy:
    external: true
  internal:
    external: false
    
services:
  files:
    image: zate75/files
    container_name: files
    restart: always
    entrypoint: ["./files","-d","./stuff"]
    labels:
      - traefik.backend=files
      - traefik.frontend.rule=Host:files.zate.org
      - traefik.docker.network=proxy
#      - traefik.port=80
    networks:
      - internal
      - proxy
    volumes:
      - ./stuff:/home/files/stuff:cached
#
